---
title: "Protected_areas_GLOBIO_0.5_to-cube_260227.Rmd"
author: "Magali Weissgerber" "Emmanuel Oceguera"
date: "2026-03-09"
output: html_document
---

```{r,eval=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Librairies

```{r}
# Load libraries
library(terra)
library(jsonlite)
library(ebvcube)

```

## Exploring the files

```{r}

# List files
list.files(
  "I:/biocon/Projects/BES-SIM 2/Data_geo/protected_areas/GLOBIO-based_PAs/raw",
  pattern = "\\.tif$",
  full.names = TRUE
  )

# /aligned_tifs_byte

```

## built and export the .json file
```{r}

# Build json 
GLOBIO_PA_cubes_json <- list(
  
  code = "",
  message = "Preliminary metadata",
  
  data = list(
    
    id = "",
    naming_authority = "The German Centre for Integrative Biodiversity Research (iDiv) Halle-Jena-Leipzig",
    title = "Protected areas (BES-SIM 2 GLOBIO, 0.5 degree)",
    product_version = "pending",
    doi = "pending",
    date_created = "_____",
    date_issued = "pending",
    summary = "Protection status of land expressed as suitability for land use change from the GLOBIO model. This
    version is aggregated to a 0.5 degree spatial resolution for the BES-SIM 2 Nature Futures scenarios.",
    keywords = "pending",
    references = "N/A",
    
    source = "Protected area maps expressed as the suitability for land use change from the GLOBIO model",
    
    coverage_content_type = "modelResult",
    project_name = "BES-SIM 2",
    project_url = "https://bes-sim.org/",
    
    creator = list(
      creator_name = "Rob Alkemade",
      creator_email = "rob.alkemade@pbl.nl",
      creator_institution = "PBL Netherlands Environmental Assessment Agency",
      creator_url = "https://orcid.org/rob.alkemade@pbl.nl"
    ),
    
    contributor_name = "Michel Bakkanes",
    
    license = "https://creativecommons.org/licenses/by/4.0",
    
    publisher = list(
      publisher_name = "Magali Weissgerber",
      publisher_email = "magali.weissgerber@idiv.de",
      publisher_institution = "German Centre for Integrative Biodiversity Research (iDiv)",
      publisher_url = "https://orcid.org/0000-0002-2999-055X"
    ),
    
    ebv = list(
      ebv_class = "Cross-cutting",
      ebv_name = "Cross-cutting"
    ),
    
    ebv_entity = list(
      ebv_entity_type = "Protection as suitability for LU change",
      ebv_entity_scope = "This dataset contains the protection status of land as the suitability for land use change. Protection corresponds to a suitability value of 0.",
      ebv_entity_classification_name = "pending",
      ebv_entity_classification_url = "pending",
      ebv_entity_names = "Suitability",
      ebv_entity_taxonomy_levels = "pending",
      ebv_entity_taxonomy_table = "pending"
    ),
    
    ebv_metric = list(
      ebv_metric_1 = list(
        `:standard_name` = "Suitability for LU change",
        `:long_name` = "Land protection records whether a grid cell is suitable for land use change. Original raster values are 0 (protection), 95 and 100. In this 0.5 degree product, values represent the mean aggregated suitability across all input cells.",
        `:units` = "mean suitability score"
      )
    ),
    
    ebv_scenario = list(
      ebv_scenario_classification_name = "The scenarios were built based on the values of nature outlined in the Nature Futures Framework for BES-SIM 2. Protection only applies to NfN and NfS.",
      ebv_scenario_classification_version = "N/A",
      ebv_scenario_classification_url = "N/A",
      
      ebv_scenario_1 = list(
        `:standard_name` = "Nature for Nature",
        `:long_name` = "Nature for Nature"
      ),
      
      ebv_scenario_2 = list(
        `:standard_name` = "Nature for Society",
        `:long_name` = "Nature for Society"
      )
    ),
    
    ebv_geospatial = list(
      ebv_geospatial_scope = "Global",
      ebv_geospatial_description = "N/A"
    ),
    
    geospatial_lat_resolution = "pending",
    geospatial_lon_resolution = "pending",
    geospatial_bounds_crs = "pending",
    geospatial_lat_min = "pending",
    geospatial_lon_min = "pending",
    geospatial_lat_max = "pending",
    geospatial_lon_max = "pending",
    
    time_coverage = list(
      time_coverage_resolution = "Single time",
      time_coverage_start = "2020-01-01",
      time_coverage_end = "2020-01-01"
    ),
    
    ebv_domain = "Terrestrial",
    comment = "0.5 degree mean-aggregated version of the original GLOBIO-based protected area suitability rasters.",
    
    dataset = list(
      pathname = "pending",
      download = "pending",
      metadata_json = "pending",
      metadata_xml = "pending"
    ),
    
    file = list(
      download = "pending"
    )
  )
)

# Write Jsin ti fiel
write_json(GLOBIO_PA_cubes_json, "GLOBIO_PA_cubes_0.5_metadata.json",
           pretty = TRUE, auto_unbox = TRUE)

# Export json 
output_folder <- "I:/biocon/Projects/BES-SIM 2/Data_geo/protected_areas/GLOBIO-based_PAs/scripts"

write_json(
  GLOBIO_PA_cubes_json,
  file.path(output_folder, "GLOBIO_PA_cubes_0.5_metadata.json"),
  pretty = TRUE,
  auto_unbox = TRUE
)

```

## Build nc

# 1. Define paths ----

```{r}
json_globio <- "I:/biocon/Projects/BES-SIM 2/Data_geo/protected_areas/GLOBIO-based_PAs/scripts/GLOBIO_PA_cubes_0.5_metadata.json"
pathin_globio <- "I:/biocon/Projects/BES-SIM 2/Data_geo/protected_areas/GLOBIO-based_PAs/raw" 
nc_globio <- file.path("I:/biocon/Projects/BES-SIM 2/Data_geo/protected_areas/GLOBIO-based_PAs/cubes/alkemade_ecostr_idTBD_test.nc")

```

# 2. Plot data and check data ----

```{r}

# Define valid scenario–approach pairs
scenario_approach <- data.frame(
  scenario   = c("Nature for Nature", "Nature for Society"),
  approach = c("HE", "WE"),
  stringsAsFactors = FALSE
)

# Define other dimensions
entities <- "Suitability"
metrics  <- "Suitability for LU change"

# Build only valid combinations
grid_globio <- merge(
  scenario_approach,
  expand.grid(
    entities = entities,
    metrics  = metrics,
    stringsAsFactors = FALSE
  )
)

# Build filenames
grid_globio$tif <- paste0(
  "pa_reduce", "_",
  grid_globio$approach, "_", "2070", ".tif"
)

# Build full paths
grid_globio$path <- file.path(
  pathin_globio,
  grid_globio$tif
)

# Check which files actually exist
grid_globio$exists <- file.exists(grid_globio$path)

# Inspect missing files
grid_globio[!grid_globio$exists, ]

# Create "tif_paths" object
tif_paths <- grid_globio$path

# Explore one of the tif files
globio_NfN <- rast(tif_paths[1])
ext(globio_NfN)
res(globio_NfN)

globio_Nfs <- rast(tif_paths[2])
ext(globio_Nfs)
res(globio_Nfs)

```

```{r}
# As we can see above the two raster have different resolution
# We resample in order to aling the rasters

# Template 
globio_NfN

globio_Nfs_aligned <- terra::resample(
  globio_Nfs,
  globio_NfN,
  method = 'near')

# # Write raster
# writeRaster(
#   globio_Nfs_aligned, 
#   "I:\\biocon\\Projects\\BES-SIM 2\\Data_geo\\protected_areas\\GLOBIO-based_PAs\\raw\\aligned/pa_reduce_WE_2070.tif", 
#   overwrite = TRUE,
#   gdal= "COMPRESS=DEFLATE"
#   )

# Come back to the original name but with right ext
globio_NfN <- globio_Nfs_aligned


```


# 3. Aggregate rasters to 0.5 degree ----
```{r}

r0 <- rast(grid_globio$path[1])

fact_x <- round(0.5 / res(r0)[1])
fact_y <- round(0.5 / abs(res(r0)[2]))

cat("Aggregation factors:", fact_x, fact_y, "\n")


```
```{r}

pathout_agg <- "I:/biocon/Projects/BES-SIM 2/Data_geo/protected_areas/GLOBIO-based_PAs/raw/0.5_degrees_test"

# Aggregate all rasters to 0.5 degree
for (i in seq_len(nrow(grid_globio))) {
  
  r <- rast(grid_globio$path[i])
  
  r_agg <- terra::aggregate(
    r,
    fact = c(fact_x, fact_y),
    fun = mean,
    na.rm = TRUE
  )
  
  out_name <- sub("\\.tif$", "_05deg.tif", basename(grid_globio$path[i]))
  out_path <- file.path(pathout_agg, out_name)
  
  writeRaster(
    r_agg,
    out_path,
    datatype  = "FLT4S",
    overwrite = TRUE,
    gdal = c("COMPRESS=DEFLATE")
  )
  
  grid_globio$path_agg[i] <- out_path
  
  rm(r, r_agg)
  gc()
  
  message("Aggregated: ", grid_globio$tif[i])
}

```

```{r}

# Check aggregated raster
globio_NfN_agg <- rast(grid_globio$path_agg[1])
globio_Nfs_agg <- rast(grid_globio$path_agg[2])

# # Template 
# globio_NfN_agg
# 
# globio_Nfs_aligned <- terra::resample(
#   globio_Nfs_agg,
#   globio_NfN_agg,
#   method = 'near')
# 
# # Write raster
# writeRaster(
#   globio_Nfs_aligned,
#   "I:\\biocon\\Projects\\BES-SIM 2\\Data_geo\\protected_areas\\GLOBIO-based_PAs\\raw\\0.5_degrees_test/pa_reduce_WE_2070_05deg.tif",
#   overwrite = TRUE,
#   gdal= "COMPRESS=DEFLATE"
#   )
# 
# # Come back to the original name but with right ext
# globio_NfN <- globio_Nfs_aligned
# 




```
# 4. Create EBVCube netCDF ----

```{r}
# Defining  fillvalue
fv <- -3.4e+38

# Spatio temporal setting
res1 <- res(globio_NfN_agg)
ext <- as.vector(ext(globio_NfN_agg))
# ext <- c(-180, 180.486111111111, -90.4916666666666, 90.0000000000002)
epsg <- 4326
prec <- "float"


# Create the netCDF structure (no data yet)
ebv_create(
  jsonpath = json_globio,
  outputpath = nc_globio,
  entities = entities, #alternative: csv (see help-page)
  epsg = epsg,
  extent = ext,
  resolution = res1,
  timesteps = "2000-01-01",
  fillvalue = fv,
  prec = prec,
  force_4D = TRUE,
  overwrite = TRUE,
  verbose = FALSE 
  )

# Check out the (still empty) datacubes that are available
dc_new <- ebv_datacubepaths(nc_globio, verbose=TRUE)
print(dc_new)

# Check metadata
prop <- ebv_properties(nc_globio, scenario = 1, metric = 1, verbose=TRUE)
print(prop@spatial)
```

# 5. Populate EBVCube netCDF ----

```{r}


# Loop to fill the cubes
for (i in seq_len(nrow(grid_globio))) {
  
  path <- grid_globio$path_agg[i]
  
  if (!file.exists(path)) {
    warning("Missing file: ", path)
    next
  }

  ebv_add_data(
    filepath_nc = nc_globio,
    metric      = 1,
    scenario    = grid_globio$scenario[i],
    entity      = grid_globio$entities[i],
    timestep    = 1,
    data        = path,
    band        = 1,
    ignore_RAM = TRUE,
    raw = TRUE,
    verbose = FALSE
  )
  
  message("Added: ",
          grid_globio$scenario[i], " | ",
          grid_globio$metrics[i], " | ",
          grid_globio$entities[i])
}

```
